let data: Record<string, string> = {
    "E5": "Englisch",
    "E": "Englisch",
    "D": "Deutsch",
    "M": "Mathematik",
    "S8": "Spanisch",
    "S0": "Spanisch",
    "MU": "Musik",
    "SW": "Sozialwissenschaften",
    "G": "Geschichte",
    "GE": "Geschichte",
    "K": "Kunst",
    "KU": "Kunst",
    "PH": "Physik",
    "CH": "Chemie",
    "BI": "Biologie",
    "BIO": "Biologie",
    "B": "Biologie",
    "IF": "Informatik",
    "INF": "Informatik",
    "SP": "Sport",
    "PA": "Pädagogik",
    "ER": "Religion",
    "KR": "Religion",
    "RELI": "Religion",
    "EL": "Ernährungslehre",
    "PL": "Philosophie",
    "ET": "Ethik",
    "PO": "Politik",
    "VK": "Vertifungskurs",
    "LI": "Literatur",
}

export default data;
