services:
  checkin:
    container_name: checkin
    build: .
    restart: always
    depends_on:
      - checkin-db
    environment:
      APP_NAME: CheckIn
      APP_ENV: local
      # APP_KEY is read from .env
      APP_DEBUG: true
      APP_URL: http://localhost:3000

      DB_CONNECTION: pgsql
      DB_HOST: checkin-db
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

      SESSION_DRIVER: database
    ports:
      - "3000:80"
    volumes:
      - ".:/var/www/html"

  checkin-db:
    container_name: checkin-db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - "checkin_pgdata:/var/lib/postgresql/data"

volumes:
  checkin_pgdata:
    name: checkin_pgdata
