services:
  web:
    container_name: checkin
    image: ghcr.io/davidcraftdev/checkin:stable
    restart: always
    depends_on:
      - db
    environment:
      - TZ=Europe/Berlin
      # Please replace the following environment variables with your own values, you need to set the same values in the db service
      - POSTGRES_PRISMA_URL=postgres://postgres:postgres@db:5432/postgres
      # Please replace the following environment variables with your own random secret
      - NEXTAUTH_SECRET=YOUR_SECRET
      # Please set own default admin credentials
      - DEFAULT_ADMIN_USERNAME=OwnUsername
      - DEFAULT_ADMIN_PASSWORD=OwnPassword
      # Enable the study time feature (true/false). Once enabled, the feature should not be disabled.
      - STUDYTIME=false
      # The LDAP auth feature may not work with your envorinment. Please test it before using it in production, and when it not works, ask for help!
      # Use the LDAP auth feature instead of the own user management from the CheckIN (true/false). Please only enable before the first start of the CheckIN, otherwise the own user management will be disabled and you can't login with the default admin credentials.
      - USE_LDAP=false
      # LDAP server URL starting with ldap:// or ldaps://
      - LDAP_URI=ldap://ldap.example.com
      # LDAP bind DN credentials
      - LDAP_BIND_DN=cn=admin,dc=example,dc=com
      - LDAP_BIND_PASSWORD=example
      # LDAP search base
      - LDAP_SEARCH_BASE=dc=example,dc=com
      # LDAP user search filter
      - LDAP_USER_SEARCH_FILTER=(cn=*)
      # Create local admin user if LDAP auth is enabled (true/false) The user will be created with the default admin credentials, the username will start with "local/"
      - LDAP_CREATE_LOCAL_ADMIN=true
      # Exßperimental feature: Automatically detect users group LDAP groups (true/false)
      - LDAP_AUTO_GROUPS=false
      # Experimental feature: Automatically detect users needed studyTimes from LDAP groups (true/false)
      - LDAP_AUTO_STUDYTIME=false
    ports:
      - "3030:3000"
  db:
    container_name: checkin-db
    image: postgres:16-alpine
    restart: always
    environment:
      - TZ=Europe/Berlin
      # Please replace the following environment variables with your own values, you need to set the same values in the checkin service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - checkin_pgdata:/var/lib/postgresql/data

volumes:
  checkin_pgdata:
    name: checkin_pgdata
